### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/tongfang-hackintosh-utility#10]
can you please think about the possibility to convert all you work, to english language?

tong fang laptops are exported to various countries around the world including here (brazil)

i suggest english because i'ts some kind of a global language, most of people know a bit of english, but chinese is very hard, even for google translator kkk

**Comment by kirainmoe** [comment]
This app will display in English when your system language is not Chinese. Is there anything else should I do?

**Comment by rodgomesc** [comment]
sorry, my mistake
