### ISSUE TITLE
Can you add my laptop model to the TongFang Hackintosh Utility?

### ISSUE THREAD

**Issue by sutsurup** [kirainmoe/tongfang-hackintosh-utility#11]
Hi kirainmoe, first of all, thank you for supporting Hackintosh. I started following you at the suggestion of my Se7Touch friend. I love your works so much. Congratulations. I recently installed an macOS on a Monster Laptop using your TongFang Hackintosh Utility. As you know, the MONSTER is sold in Turkey. Can you add my laptop model to the TongFang Hackintosh Utility?

Laptop Name: MONSTER Tulpar T7 V20.1
Barebone Number: GK7CP6R
There's no difference between V19.3. Just minor changes like SSD brand and RAM brand.
It just doesn't read the SATA HDD on the macOS setup screen. I told you how to solve it [here](https://github.com/sutsurup/MONSTER-Hackintosh#kurulum-sonrası-yararlanabileğiniz-rehberaraçlar-isteğe-bağlı). (HDD Tanıtma Talimatları)

I created the first MONSTER GitHub Repository in Turkey, to help the people here.
https://github.com/sutsurup/MONSTER-Hackintosh
Detailed information about hardware: https://github.com/sutsurup/MONSTER-Hackintosh#donanım
I've written a guide to how to Hackintosh other MONSTER devices with the TongFang Hackintosh Utility. I'm waiting your Feedback. Thank you.

**Comment by kirainmoe** [comment]
Thanks for your feedback, your tutorial is rather than detailed. This model will be added to the next release of Tongfang Hackintosh Utility.
