### ISSUE TITLE
Details for options 

### ISSUE THREAD

**Issue by PhantomR** [kirainmoe/tongfang-hackintosh-utility#27]
I apologize for posting an issue for this, but could you please explain what the options
Preliminary support for MacOS 11.0
Load Apple GuC Firmware
CPU Best Performance Mode
actually do?

Do I need to enable the first one if I have Big Sur? :)

Also, forgive me if I am taking too much of your time, but may I ask why there are so many DSDT-s (and what do they actually do)? I have enabled the following options: Preliminary MacOS 11 Support, Intel Wi-Fi, Intel Bluetooth, Disable Unsupported NVME (also, how do I know if I have an unsupported NVME?), Load NVMEFix and Android USB Tethering.

I do not know what the following do:
SSDT-AWAC.aml
SSDT-DNVME.aml - how does this actually work? this is for those unsupported NVMEs. I have an Intel 660p 512GB NVME..
SSDT-GPRW.aml
SSDT-HPET.aml
SSDT-PMC.aml
SSDT-PWBTN.aml
SSDT-UIAC.aml
SSDT-USTP.aml

I understand these:
SSDT-EC-USBX.aml - this is mentioned in the Dortania guide
SSDT-PLUG.aml - mentioned in the Dortania guide
SSDT-PNLF.aml - mentioned in the Dortania guide
SSDT-BATT.aml - this must be for the battery indicator
SSDT-DDGPU.aml - this must be to disable the dGPU

Thank you so much for sharing your amazing project.

**Comment by kirainmoe** [comment]
> I apologize for posting an issue for this, but could you please explain what the options
Preliminary support for MacOS 11.0
Load Apple GuC Firmware
CPU Best Performance Mode
actually do?

- Preliminary support for macOS 11.0 will add / change some properties and boot args to make the config be able to boot macOS Big Sur and Big Sur recovery.
- Load Apple GuC firmware will add `igfxfw=2` boot arg to load Apple GuC firmware for UHD630. GuC firmware can greatly improve the performance of the integrated gpu, but it may cause sleep/wake failure on some specific device.
- CPU best performance mode will load a different CPU performance scheme which unlocked the frequency and TDP.

> Do I need to enable the first one if I have Big Sur? :)

Of course.

> also, how do I know if I have an unsupported NVME?

These NVMe SSDs are known to be incompatible with macOS and will cause kernel panic:

- Samsung PM981 / PM981A, SN starts with MZVLB
- Micron 2200s series
- Intel Optane SSD

No need to check disable nvme if you are not using these SSDs.

> I do not know what the following do:
SSDT-AWAC.aml
SSDT-DNVME.aml - how does this actually work? this is for those unsupported NVMEs. I have an Intel 660p 512GB NVME..
SSDT-GPRW.aml
SSDT-HPET.aml
SSDT-PMC.aml
SSDT-PWBTN.aml
SSDT-UIAC.aml
SSDT-USTP.aml

Refer to kirainmoe/hasee-tongfang-macos/OC/config.plist `ACPI->Add` to know the function of each ACPI patch.

**Comment by PhantomR** [comment]
Thank you so much, can't believe I did not think of reading the plist.. I am a little confused why the AWAC DSDT is needed (Dortania guide does not mention it is needed for Coffee Lake). Same holds for HPET, I think.

 Also, what would the SSDT-PMC used for (description mentions it is OC NVRAM Implementation related) ? Is there no good NVRAM on the motherboard for these laptops?

Lastly, is the SSDT-USTP the same as SSDT-GPIO here https://github.com/dortania/Getting-Started-With-ACPI/blob/master/extra-files/decompiled/SSDT-GPI0.dsl ?

Would it be possible to obtain the DSL files, please?

**Comment by kirainmoe** [comment]
Well, you should know that dortania's guide is just a template for most users to get start, but to build a more perfect hackintosh there are more things to be done. 

- 9th gen Tongfang laptops' motherboard requires SSDT-AWAC else it will stuck on boot. 
- HM370 motherboard do not have the native NVRAM support, in order to fix this we need SSDT-PMC patch. 
- SSDT-USTP is a patch for VoodooI2C.kext to make the touchpad work on GPIO interrupt mode. It is different to the SSDT-GPIO.

Original .dsl files can be found on https://github.com/kirainmoe/hasee-tongfang-macos/tree/oc-general/Docs/ACPI%20source

**Comment by PhantomR** [comment]
Thank you so much once again. I understand the guide is only a start, but I do think they say PMC and AWAC are only needed.for 9th gen Intel. I have 8th gen.. I should not need them, right?
https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#laptop

I am really confused by PMC, though, since their PMC page says it IS needed for H370, though no Mobile versions are specified..
https://dortania.github.io/Getting-Started-With-ACPI/Universal/nvram.html
The motherboard is also mentioned for AWAC...
https://dortania.github.io/Getting-Started-With-ACPI/Universal/awac.html
So, is the table at the very first link wrong or am I missing something?

I noticed there is also an RTC patch in the config.. what is that for?

And what was additionally done to have dual boot with Windows support?

I really appreciate the time you spent helping me and also making these tools/configs.. although I feel bad wasting more or of your time, I really want to understand.

**Comment by kirainmoe** [comment]
SSDT-AWAC has no effect to 8th gen laptops, since this repository is made for both 8th gen and 9th gen  laptops, this patch is included. You can disable it if you use 8th gen device or just leave it enabled as is.

As I mentioned above, dortania's guide is just for reference, there may be inconsistency (or wrong) in that guide.  If you want to know whether some patches are necessary or not, the best way is to test it by yourself. In this case, if you disable SSDT-PMC.aml then native NVRAM will stop working, so it is needed.

RTC patch is to fix the random wake while sleeping.

Nothing addition need to be done to have Windows dual boot for this config. I2C touchpad patch is different from every machine, you can read VoodooI2C's document. 

For 9th gen i7 laptops, using MacbookPro15,1 SMBIOS will make the i7 CPU be recognized as i9 in macOS, so use MacbookPro15,3.

**Comment by PhantomR** [comment]
> SSDT-AWAC has no effect to 8th gen laptops, since this repository is made for both 8th gen and 9th gen laptops, this patch is included. You can disable it if you use 8th gen device or just leave it enabled as is.
> 
> As I mentioned above, dortania's guide is just for reference, there may be inconsistency (or wrong) in that guide. If you want to know whether some patches are necessary or not, the best way is to test it by yourself. In this case, if you disable SSDT-PMC.aml then native NVRAM will stop working, so it is needed.

I actually managed to boot without both AWAC and PMC (I have an i7 8750H - 8th gen Overpowered 17+) but I was NOT using this config (I got here afterwards because I wanted to make mine better / completely replace it with yours since I am sure it is way better done than what I did). I used Dortania's Virtual Machine route for Big Sur (using real SSD as virtual hard disk and installing to it from VirtualBox) since installing directly always lead me to some 'diskarbitrationd' error. Can I say for sure I do not need PMC in this case? 

> RTC patch is to fix the random wake while sleeping.
OK. I would really love to know how you found this and also the ACPI patches in the plist (like _WAK1 to ZWAK and all the otehrs).

 
> Nothing addition need to be done to have Windows dual boot for this config. 

Regarding Windows, what I wanted to ask is what was made in this config specifically to allow dual boot siance I read it is supported out of the box with this config.

> I2C touchpad patch is different from every machine, you can read VoodooI2C's document.

I skimmed a little through their docs, but didn't seem to find anything about USTP :( ..
 
> For 9th gen i7 laptops, using MacbookPro15,1 SMBIOS will make the i7 CPU be recognized as i9 in macOS, so use MacbookPro15,3.

So I understand the MacbookPro15,3 is only needed for 9th gen, good :)

Looks like my questions are endless, but if I am not annoying enough yet, may I also ask what is the role of all the Broadcom kexts (I have Intel Bluetooth and Wi-Fi) and also what is the PS2 RehabMan Kext (do I need this  RehabMan kext if I have an I2C touchpad)?

**Comment by kirainmoe** [comment]
I recommend you should include PMC in your config. If native NVRAM cannot properly work on macOS, you will need to use inir.rc script to emulate NVRAM, or you will meet errors in some functions (e.g. Find My Mac, Bootcamp).

ACPI patches can be found everywhere on the Internet, for example [rehabman's repository](https://github.com/RehabMan/Laptop-DSDT-Patch) and [OC-little (only Chinese)](https://github.com/daliansky/oc-little). 

ACPI patches should include OS judgement, which will make those patches take effect on macOS: `If (_OSI("Darwin")) {}`.

`USTP` property is not a universal name, it only appears in Tongfang laptops with I2C touchpad . I cannot explain you how `USTP = 1` make the VoodooI2C work on GPIO interrupt mode since this process is so long and a little complicated, but this progress is the same as how to patch DSDT to make VoodooI2C work which is mentioned in VoodooI2C's document.

Broadcom kexts are for broadcom & apple vendor wireless card. Some laptop with PS/2 touchpad (not I2C touchpad) requires Rehabman's VoodooPS2 driver to make touchpad work.

**Comment by PhantomR** [comment]
> I recommend you should include PMC in your config. If native NVRAM cannot properly work on macOS, you will need to use inir.rc script to emulate NVRAM, or you will meet errors in some functions (e.g. Find My Mac, Bootcamp).

Could not having PMC be the reason Find My seems unable to locate me? (stuck on "Locating..")?

> ACPI patches can be found everywhere on the Internet, for example [rehabman's repository](https://github.com/RehabMan/Laptop-DSDT-Patch) and [OC-little (only Chinese)](https://github.com/daliansky/oc-little).
> 
> ACPI patches should include OS judgement, which will make those patches take effect on macOS: `If (_OSI("Darwin")) {}`.
> 
> `USTP` property is not a universal name, it only appears in Tongfang laptops with I2C touchpad . I cannot explain you how `USTP = 1` make the VoodooI2C work on GPIO interrupt mode since this process is so long and a little complicated, but this progress is the same as how to patch DSDT to make VoodooI2C work which is mentioned in VoodooI2C's document.

I understand it might be hard to explian, but was hoping you could point me to a discussion somewhere else I could maybe read. However, may I ask if the effect of setting USTP to 1 is any different than using the SSDT-GPIO I mentioned in an earlier reply? The description of the GPIO SSDT is: "This SSDT is used to force enable our GPI0 for VoodooI2C to connect onto." My touchpad works with the GPIO SSDT, would using the USTP one make it work better or something? What I do not have is the quick turn off option by double tapping the top left corner of the touchpad.. does USTP help with this?
 
> Broadcom kexts are for broadcom & apple vendor wireless card. Some laptop with PS/2 touchpad (not I2C touchpad) requires Rehabman's VoodooPS2 driver to make touchpad work.
Awesome :) So, I guess I do not need any of them.

**Comment by kirainmoe** [comment]
> Could not having PMC be the reason Find My seems unable to locate me? (stuck on "Locating..")?

"Find my Mac" switch in iCloud will be disabled when reboot.

>  However, may I ask if the effect of setting USTP to 1 is any different than using the SSDT-GPIO I mentioned in an earlier reply? 

The difference between directly setting `USTP` to 1 and using `SSDT-GPIO.aml` is that the former make the touchpad work on APIC interrupt mode and the latter make it work on GPIO interrupt mode. The two modes have the same effect. APIC interrupt mode requires less modification (in this case just set `USTP` to 1), however there are few devices support APIC interrupt (luckily tongfang devices support it), so many devices use GPIO interrupt mode. 

> What I do not have is the quick turn off option by double tapping the top left corner of the touchpad.. does USTP help with this?

USTP does not do this, but with `TongfangKeyboardUtility.kext` and `TongfangFnDaemon` installed will fix the double tap enable/disable touchpad.

> What is CPUFriend used for? Is it for turbo boost or something?

https://github.com/acidanthera/CPUFriend

**Comment by PhantomR** [comment]
Many thanks. I had read the description on the CPUFriend page a little, but decided to ask for more details.. in the meantime I found it is also used in the Dortania guide so there are a few more explanations there.

Regarding the TongfangKeyboardUtility,  where could I find the source for it? Is it this (renamed)? VoodooWMI? https://github.com/Goshin/VoodooWMI

**Comment by kirainmoe** [comment]
Yes, it is renamed to VoodooWMI.

**Comment by kirainmoe** [comment]
Closing this issue for being inactive.

**Comment by PhantomR** [comment]
I apologize for not answering in such a long time. Many thanks for all your help, all is clear for now :).
