### ISSUE TITLE
黑苹果客户端bug

### ISSUE THREAD

**Issue by HWJGG** [kirainmoe/tongfang-hackintosh-utility#28]
在黑苹果下（10.15.7）无法下载Intel驱动包

**Comment by kirainmoe** [comment]
https://github.com/kirainmoe/hasee-tongfang-macos/issues/85

执行以下命令：
```
rm -rf ~/.tfu
```
然后重试下载。如果问题依旧，请检查你是否能正常访问 cdn.jsdelivr.net

**Comment by kirainmoe** [comment]
Should be fixed in 3.0.0-gm
