### ISSUE TITLE
Just choose a colour not a sequence

### ISSUE THREAD

**Issue by wifiuk** [kirainmoe/tongfang-hackintosh-utility#3]
I have board version 0.01 and although it changes the keyboard to a sequence, it would be good if you could allow just a single colour or a custom option. There was a Chinese software that worked for windows but not for linux.

**Comment by wifiuk** [comment]
i am using that, but it wont allow a single colour, i can have pulsing, rainbow , waves etc.

**Comment by wifiuk** [comment]
http://www.mechrevo.com/en/plus/search.php?keyword=MR%20X6TI%E5%A4%9A%E5%BD%A9%E7%89%88&kwtype=0&searchtype=title&typeid=25&exact=1
If i remember correctly i think this works for windows but not linux

**Comment by wifiuk** [comment]
![image](https://user-images.githubusercontent.com/3785545/72761216-3c0f5f00-3bd3-11ea-8007-3fef6a481e90.png)

**Comment by wifiuk** [comment]
![image](https://user-images.githubusercontent.com/3785545/72761267-62cd9580-3bd3-11ea-9418-f0499a4c18ed.png)

**Comment by kirainmoe** [comment]
Have you tried the latest release?

**Comment by wifiuk** [comment]
Yes. Same issue

>

**Comment by kirainmoe** [comment]
OK, I understand your requirement. However, the program should know the controlling code by capturing the packet sent by the app, but my laptop does not support set a color for each key, thus I can not make it.

**Comment by wifiuk** [comment]
Anyway I can help?

>

**Comment by kirainmoe** [comment]
Unless you know the principle how the ITE chip controls the keyboard light completely. This could be hard to do and require experiments. To archive this we need to use some analyzer software (e.g. `free-usb-analyzer`) to capture the package sent by the app when performing every action.
