### ISSUE TITLE
With Microsoft OneDrive installed, Desktop folder location causes EPERM error

### ISSUE THREAD

**Issue by Hhavoc** [kirainmoe/tongfang-hackintosh-utility#31]
With Microsoft OneDrive installed, ~/Desktop folder is relocated to C:\Users\jay\OneDrive\Desktop\

Selected Configuration: EVOO LP5, 
MacOS: Big Sur
Wifi card: Apple
Screen: 1920 x 1080 (144khz)
Personalize: Enable Bootchime

Result:
Error: EPERM: operation not permitted, open 'C:\Users\jay/Desktop/Tongfang_EFI/OpenCore.zip'

Notice the backslashes are wrong direction after Desktop folder.
I manually created a Tongfang_EFI folder in a C:\Users\jay\Desktop\ directory, even though OneDrive captures the "regular" desktop folder, but this did not resolve the error.

**Comment by kirainmoe** [comment]
Will be fixed in the next release version.

For now please try to unset Desktop as a backup target.
