### ISSUE TITLE
无线网卡

### ISSUE THREAD

**Issue by hbs17177355222** [kirainmoe/tongfang-hackintosh-utility#33]
在引导界面可以使用intel无线，安装完成进系统就用不了了

**Comment by kirainmoe** [comment]
这是 itlwm 驱动本身稳妥人，请左转 OpenIntelWireless/itlwm 查看文档寻找解决方案或反馈，与 efi 无关。

**Comment by hbs17177355222** [comment]
好的，谢谢啦
