### ISSUE TITLE
机械革命X3-S无声音，设置启动模拟有声音，但进入系统显示无声音硬件

### ISSUE THREAD

**Issue by jackyGang** [kirainmoe/tongfang-hackintosh-utility#34]
机械革命X3-S无声音，设置启动模拟有声音，但进入系统显示无声音硬件

**Comment by kirainmoe** [comment]
十代机械革命设备更换了声卡，不再使用 ALC269。没有设备无法适配，请自行参照 AppleALC 定制教程，定制声卡 codec，并使用 ALCPluginFix / ComboJack 修复耳机。

**Comment by jackyGang** [comment]
好的，刚开始弄这个，很多不清楚，给你填麻烦了，我找一下教程参照试试，如果方便的话，可否提供一份处理好的，37377522@qq.com
