### ISSUE TITLE
Can you disable SK hynix P31 nvme ssd when boot on macOS?

### ISSUE THREAD

**Issue by Waterticket** [kirainmoe/tongfang-hackintosh-utility#36]
I'm using SK hynix gold P31 1tb nvme storage.

When I tried to boot with this utility, it crashes because of "NVMe fatal error".
I know this nvme doesn't support macOS, but I should connect on motherboard because I use this nvme for boot my Windows.

#27 In this issue, you said SSDT-DNVME.aml file disable unsupported nvme devices.
Can you disable this nvme device too?

Thanks!

**Comment by kirainmoe** [comment]
You can just switch to another m.2. slot and check "Disable incompatible NVMe" option.
