### ISSUE TITLE
Tongfang Hackintosh Utility Device Choice

### ISSUE THREAD

**Issue by osxfr33k** [kirainmoe/tongfang-hackintosh-utility#42]
I have the OP-LP3 GK7CN6S which is the 17 inch version of the 15 inch OP-LP2 model GK5CN6Z but isn't the processor in mine different from GK5CN6Z?   I think mine is 9th generation or not, Intel Core i7-8750H?   I am unsure which model to choose from during the configuration I am guessing to choose model GK5CN6Z since there is no choice for GK7CN6S but is that the one I should choose or choose a different model and if so, which one?  Will you be adding this model to the utility eventually?  Edited: Actually the specs are the same in those models I jus have the 17 inch LCD version and its 8th generation CPU.

**Comment by kirainmoe** [comment]
Tongfang barebone models are various, thus I cannot cover all models. There is a statement about how to choose the model in the readme.md of hasee-tongfang-macos repo:

> Currently, this config is known to be compatible with all 8th / 9th generation Tongfang barebones (except Intel Tongfang QC7, although some barebones models are not listed in the following table). For example:

Barebone | Platform Generation
-- | --
GK5CN5X, GK5CN6X | 8th
GK5CN5Z, GK5CN6Z | 8th
GK7CN6S, GK7CN5S | 8th
GI5CN54, GJ5CN64 (PS/2 Touchpad) | 8th
GK5CP6Z, GK5CP5Z | 9th
GK5CP6X, GK5CP5X | 9th
GK7CP6R, GK7CP0R | 9th
GK5CP5V, GK5CP6V | 9th

> If you have 8th gen platform laptops with I2C touchpad but the barebone model is not in the list, try one of GK5CN6X, GK5CN6Z (GTX 1060) or GK5CN5X, GK5CN5Z (GTX 1050Ti).  
If you have 8th gen platform laptops with PS/2 touchpad but the barebone model is not in the list, try one of GJ5CN64 (GTX 1060) or GI5CN54 (GTX 1050Ti).  
If you have 9th gen platform laptops but the barebone model is not in the list, try one of GK7CP6R, GK5CP6X, GK5CP5X, GK5CP6V, GK5CP5V, GK5CP6Z, GK5CP5Z...

**Comment by osxfr33k** [comment]
Thanks!
