### ISSUE TITLE
Linux Keyboard

### ISSUE THREAD

**Issue by CuriousxOctopus** [kirainmoe/tongfang-hackintosh-utility#52]
Good day! Can you help me understand what I need to do to install this program to change lights in Linux? 
Thank you!

**Comment by kirainmoe** [comment]
We don't provide a prebuilt binary for Linux now in 3.x release. If you use Linux, you can:

## Build the binary by yourself

Make sure Node.js & npm is installed.

```sh
# clone repo
git clone https://github.com/kirainmoe/tongfang-hackintosh-utility utility
cd utility

# build front-end
cd starbeat-core
npm install 
npm run build
cd ..
cp -r starbeat-core/build starbeat-client/build
cd starbeat-client 
npm install
rm -r package.json
mv package-win.json package.json
NODE_ENV=production npx electron-packager . \"Tongfang Hackintosh Utility\" --platform=linux --arch=x64 --out=../release --app-version=2.0 --overwrite --icon=./app.ico
```

## Use release 1.x

https://github.com/kirainmoe/tongfang-hackintosh-utility/releases/tag/v1.1.0

**Comment by CuriousxOctopus** [comment]
Thank you!
