### ISSUE TITLE
无法下载intel拓展包

### ISSUE THREAD

**Issue by IlineI** [kirainmoe/tongfang-hackintosh-utility#53]
无代理模式无法下载
有代理无论是Windows上的虚拟网卡代理还是mac上的clashXpro增强模式均无法解决
可以ping通cdn.jsdelivr.net，api.kirainmoe.com，api-aliyun.kirainmoe.com等网址
可以自动更新软件，但是怎么都没有办法下载到那个拓展包，请求给个拓展包在线地址，我自解压到.tfu
感谢您的软件让我们不用一个一个去找配置了

**Comment by kirainmoe** [comment]
可以在这里下载离线包：https://s6npaj5yw4.feishu.cn/docs/doccnVLMuVukpnR3g2GRn9Hr2Df

**Comment by IlineI** [comment]
感谢，麻烦您了
