### ISSUE TITLE
itlwn.text下载问题

### ISSUE THREAD

**Issue by saver-live** [kirainmoe/tongfang-hackintosh-utility#54]
下载不了，itlwm.text

**Comment by kirainmoe** [comment]
#53

**Comment by saver-live** [comment]
还有个问题就是替换u盘里的boot和oc文件，之后安装第一遍mac后启动项里还是只有install mac和windows两个选项，没有安装第二遍mac的那个选项

**Comment by kirainmoe** [comment]
Fixed in https://github.com/kirainmoe/tongfang-macos/commit/af8e6e44a6841fd006e60ba50dc5693a3ae70f34
