### ISSUE TITLE
"A network error is occurred. Cannot fetch update metadata."

### ISSUE THREAD

**Issue by Hhavoc** [kirainmoe/tongfang-hackintosh-utility#58]
Tried uninstalling / reinstalling, tried with Windows 10, Windows 11, versions 4.0.1 - 4.0.4.

When clicking update button, pop-up window displays, "A network error is occurred. Cannot fetch update meta-data.

Current version: 4.0.4 (build 2111061
Remote version: Failedd to fetch latest version

EFI Download Path:
C:\Users\(my user folder)\OneDrive\Desktop

App Path
C:\Users\(my user folder)\.tfu

**Comment by kirainmoe** [comment]
4.0.4 is the latest version and no update is available.
