### ISSUE TITLE
下载蓝牙驱动错误

### ISSUE THREAD

**Issue by Waynehfut** [kirainmoe/tongfang-hackintosh-utility#68]
下载蓝牙驱动错误
![截屏2022-06-01 10 24 31](https://user-images.githubusercontent.com/8127447/171315364-044fbe59-5b3b-433f-818e-6e2e9b0c39ec.png)
Failed to GET https://utility-eine.kirainmoe.com:1900/drivers/IntelBluetoothFirmware.kext-2.1.0-general-a9217e8-stable.kext.zip

**Comment by kirainmoe** [comment]
https://kirainmoe.feishu.cn/docs/doccnfvE5dW1ZyKY4PLQme0SFMe
