### ISSUE TITLE
4K补丁失效

### ISSUE THREAD

**Issue by 448031516** [kirainmoe/tongfang-hackintosh-utility#7]
APP内勾选4k屏补丁后，下载下来的配置文件无法启动，用occ查看DeviceProperties里是普通屏的设置，不知道是APP的问题还是您服务器端的问题

**Comment by kirainmoe** [comment]
我本地刚下了一次，是正常的。你再试一次

**Comment by 448031516** [comment]
> 我本地刚下了一次，是正常的。你再试一次

不好意思，我刚刚试了一遍又是正常的，好奇怪。那个plist文件是本地app生成的还是服务器端下载的呀，刚刚真的是在我勾选了4k补丁的情况下下载了一个普通屏的配置文件。。

**Comment by kirainmoe** [comment]
是在本地生成的，不是从服务端下载的
