### ISSUE TITLE
同方工具里面开启HIDPI的里面可以提供代码关闭吗

### ISSUE THREAD

**Issue by YF-97** [kirainmoe/tongfang-hackintosh-utility#8]
同方工具Tongfang Hackintosh Utility里面开启HIDPI的里面可以提供代码关闭吗？因为里面我的机型开启HIDPi后遇到了一些问题，我尝试关闭但是关闭不了，使用其他人的代码也无济于事，希望您能提供一个关闭的选项，感谢前辈的付出

**Comment by kirainmoe** [comment]
以后版本考虑添加，现在你可以先通过 https://hackintosh.kirainmoe.com/an-zhuang-hou/chang-yong-ming-ling-he-you-hua 中的方法恢复。

**Comment by YF-97** [comment]
解决啦，感谢大佬的付出，谢谢

**Comment by kirainmoe** [comment]
Feature: disable HiDPI in v2.1.4
